-- ************************************** SqlDBM: Snowflake **************************************
-- * Generated by SqlDBM: SQLDBM - Dummy - ToDrop, v24 vs v23 by Sandeep.Patil1@sainsburys.co.uk *

ALTER TABLE ADW_COLLEAGUE_HR_PL.DIM_LABOUR_PAY_CODE_HIST
    ADD COLUMN COLUMN_TEST varchar(50) NOT NULL;