-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


CREATE FILE FORMAT "ADW_PROD.ADW_PII_CUSTOMER_PL.PARQUET"
 TYPE = PARQUET;
