-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


CREATE FILE FORMAT "ADW_PROD.ADW_PII_CUSTOMER_PL.SNOWFLAKELOADER_WITH_HEADER_FILEFORMAT"
 TYPE = CSV
 FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
 NULL_IF = ( '' );
